package com.postkudigital.app.helpers;

public class Constants {
    private static final String BASE_URL = "http://13.213.192.212:8000/";
    public static final String URL_LOCATION = "https://locationfawwaz.github.io/static/api/";
    public static final String CONNECTION = BASE_URL + "api/";
    public static final String IMAGESUSER = BASE_URL + "images/user/";
    public static final String TAG = "Postku-app";
    public static String PREF_NAME = "pref_name";
    public static Double LATITUDE;
    public static Double LONGITUDE;
    public static String LOCATION;
    public static String PHONE = "phone";
    public static String NOMINAL = "nominal";
    public static String ID = "id";
    public static String INVOICE = "inv";
    public static String ID_KATEGORI = "idcat";
    public static String BUNGA = "bunga";
    public static String NAMA = "nama";
    public static String STATUS_USER = "status_user";
    public static String POSITION = "position";
    public static String METHOD = "method";
    public static String RESET = "reset";
    public static String LOGIN = "login";
    public static String INTENT_DATA = "INTENTDATA";
    public static String ADD = "add";
    public static String EDIT = "edit";
    public static String BANNER = "Detail Banner";
    public static String ARTICLE = "Detail Article";
    public static String PROVINSI = "provinsi";
    public static String KABKOTA = "kabkota";
    public static String KECAMATAN = "kecamatan";
    public static String KELURAHAN = "kelurahan";
    public static String BANK = "bank";
    public static String DISKON = "discount";
    public static String DISKON_ITEM = "diskonitem";
    public static String CUSTOMER = "pelanggan";
    public static String TIPE_ORDER = "tipeorder";
    public static String LABEL_ORDER = "labelorder";
    public static String LAP_MENU = "Laporan Menu";
    public static String LAP_STAFF = "Laporan Pegawai";
    public static String LAP_KATEGORI = "Laporan Kategori";
    public static String LAP_DISCOUNT = "Laporan Discount";
    public static String LAP_MEJA = "Laporan Meja";
    public static String LAP_PELANGGAN = "Laporan Pelanggan";
    public static String LAP_TIPE_ORDER = "Laporan Tipe Order";
    public static String LAP_LABEL_ORDER = "Laporan Label Order";
    public static String PAJAK = "pajak";
    public static String SERVICE_CHARGE = "servicefee";
    public static int CAMERTA_REQUEST = 122;
    public static int GALERY_REQUEST = 123;
    public static int PERMISSION_CAMERA_CODE = 786;
    public static int PERMISSION_WRITE_DATA = 788;
    public static int PERMISSION_READ_DATA = 789;
    public static int PERMISSION_RECORDING_DATA = 790;
    public static int CAMERA_PROFILE_REQUEST = 122;
    public static int CAMERA_TOKO_REQUEST = 123;
    public static int GALERY_PROFILE_REQUEST = 130;
    public static int GALERY_TOKO_REQUEST = 131;

}
